
[window]
opacity = 0.9
decorations = "none"  # Remove title bar; set to "full" if you prefer one

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
size = 10.0

[scrolling]
history = 10000
multiplier = 3

[cursor]
style = { shape = "Block", blinking = "On" }

[mouse]
hide_when_typing = true

[general]
# ~/.config/alacritty/alacritty.toml

import = ["~/.config/alacritty/themes/gruvbox_dark.toml"]

