
icons_format = "{icon}"

[theme]
theme = "gruvbox-dark"

[icons]
icons = "awesome4"
# ttf-firacode-nerd (For icons over the lower menu)

[[block]]
block = "net"
format = " ^icon_net_down$speed_down.eng(prefix:K) ^icon_net_up$speed_up.eng(prefix:K) "
format_alt = " $icon {$signal_strength $ssid|Wired connection} "
[block.theme_overrides]
idle_bg = "#948979"
idle_fg = "#282828"

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"
[block.theme_overrides]
idle_bg = "#282828"
idle_fg = "#ebdbb2"


[[block]]
block = "hueshift"
hue_shifter = "redshift"
step = 50
click_temp = 4000
[block.theme_overrides]
idle_bg = "#948979"
idle_fg = "#282828"

[[block]]
block = "time"
interval = 60
format = "   $timestamp.datetime(f:'%A, %B %d - %-I:%M %P') "
[block.theme_overrides]
idle_bg = "#282828"
idle_fg = "#ebdbb2"

[[block]]
block = "battery"
format = " $icon $percentage "
interval=2
full_format="$icon 100%"
device = "DisplayDevice"
driver = "upower"
[block.theme_overrides]
discharging_fg = "#ebdbb2"
discharging_bg = "#282828"
charging_fg = "#282828"
charging_bg = "#948979"
full_fg = "#282828"
empty_fg = "#ebdbb2"
empty_bg = "#282828"
